name: ChatTime
version: ${project.version}
main: de.goldendeveloper.chattime.Main
api-version: 1.16
authors: [ Golden-Developer ]
description: Zeigt die Zeit im Chat an!
website: https://Golden-Developer.de/
